# Generated by Django 3.2.13 on 2022-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='movie_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
